dictionary  = { "name": "aravinth",
 "age": 27,
 "Hometown": "Arantangi",
 "Siblings": 2}

value = {
    "products":[
        {"id":167,
"title":"300 Touring",
"description":"The 300 Touring is a stylish and comfortable sedan, known for its luxurious features and smooth performance.",
"category":"vehicle",
"price":28999.99,
"discountPercentage":7.15,
"rating":4.56,
"stock":53,
"tags":["sedans",
"vehicles"],
"brand":"Chrysler",
"sku":"SPG50KEL",
"weight":5,
"dimensions":{"width":5.03,
"height":6.98,
"depth":8.65},
"warrantyInformation":"3 year warranty",
"shippingInformation":"Ships overnight",
"availabilityStatus":"In Stock",
"reviews":[{"rating":2,
"comment":"Would not recommend!",
"date":"2024-05-23T08:56:21.626Z",
"reviewerName":"Miles Stevenson",
"reviewerEmail":"miles.stevenson@x.dummyjson.com"},
{"rating":5,
"comment":"Very happy with my purchase!",
"date":"2024-05-23T08:56:21.626Z",
"reviewerName":"Hannah Robinson",
"reviewerEmail":"hannah.robinson@x.dummyjson.com"},
{"rating":5,
"comment":"Great value for money!",
"date":"2024-05-23T08:56:21.626Z",
"reviewerName":"Harper Turner",
"reviewerEmail":"harper.turner@x.dummyjson.com"}],
"returnPolicy":"No return policy",
"minimumOrderQuantity":1,
"meta":{"createdAt":"2024-05-23T08:56:21.626Z",
"updatedAt":"2024-05-23T08:56:21.626Z",
"barcode":"4354670429851",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/1.png",
"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/2.png",
"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/3.png",
"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/4.png",
"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/5.png",
"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/6.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/vehicle/300%20Touring/thumbnail.png"},
{"id":99,
"title":"Amazon Echo Plus",
"description":"The Amazon Echo Plus is a smart speaker with built-in Alexa voice control. It features premium sound quality and serves as a hub for controlling smart home devices.",
"category":"mobile-accessories",
"price":99.99,
"discountPercentage":16.3,
"rating":3.52,
"stock":50,
"tags":["electronics",
"smart speakers"],
"brand":"Amazon",
"sku":"YHLK4W9V",
"weight":7,
"dimensions":{"width":8.1,
"height":7.74,
"depth":5.68},
"warrantyInformation":"1 month warranty",
"shippingInformation":"Ships in 1 week",
"availabilityStatus":"In Stock",
"reviews":[{"rating":4,
"comment":"Highly recommended!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Nora Mills",
"reviewerEmail":"nora.mills@x.dummyjson.com"},
{"rating":4,
"comment":"Fast shipping!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Ava Taylor",
"reviewerEmail":"ava.taylor@x.dummyjson.com"},
{"rating":4,
"comment":"Very pleased!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Aria Flores",
"reviewerEmail":"aria.flores@x.dummyjson.com"}],
"returnPolicy":"90 days return policy",
"minimumOrderQuantity":1,
"meta":{"createdAt":"2024-05-23T08:56:21.624Z",
"updatedAt":"2024-05-23T08:56:21.624Z",
"barcode":"0697313083842",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/1.png",
"https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/2.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/mobile-accessories/Amazon%20Echo%20Plus/thumbnail.png"},
{"id":137,
"title":"American Football",
"description":"The American Football is a classic ball used in American football games. It is designed for throwing and catching,making it an essential piece of equipment for the sport.",
"category":"sports-accessories",
"price":19.99,
"discountPercentage":10.28,
"rating":3.78,
"stock":48,
"tags":["sports equipment",
"american football"],
"sku":"QLDVAXMJ",
"weight":9,
"dimensions":{"width":9.74,
"height":23.16,
"depth":26.86},
"warrantyInformation":"1 month warranty",
"shippingInformation":"Ships in 2 weeks",
"availabilityStatus":"In Stock",
"reviews":[{"rating":4,
"comment":"Excellent quality!",
"date":"2024-05-23T08:56:21.625Z",
"reviewerName":"Jaxon Barnes",
"reviewerEmail":"jaxon.barnes@x.dummyjson.com"},
{"rating":4,
"comment":"Great product!",
"date":"2024-05-23T08:56:21.625Z",
"reviewerName":"Aurora Lawson",
"reviewerEmail":"aurora.lawson@x.dummyjson.com"},
{"rating":4,
"comment":"Awesome product!",
"date":"2024-05-23T08:56:21.625Z",
"reviewerName":"Evan Reed",
"reviewerEmail":"evan.reed@x.dummyjson.com"}],
"returnPolicy":"30 days return policy",
"minimumOrderQuantity":23,
"meta":{"createdAt":"2024-05-23T08:56:21.625Z",
"updatedAt":"2024-05-23T08:56:21.625Z",
"barcode":"2510402973927",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/thumbnail.png"},
{"id":11,
"title":"Annibale Colombo Bed",
"description":"The Annibale Colombo Bed is a luxurious and elegant bed frame,crafted with high-quality materials for a comfortable and stylish bedroom.",
"category":"furniture",
"price":1899.99,
"discountPercentage":0.29,
"rating":4.14,
"stock":47,
"tags":["furniture",
"beds"],
"brand":"Annibale Colombo",
"sku":"4KMDTZWF",
"weight":3,
"dimensions":{"width":28.75,
"height":26.88,
"depth":24.47},
"warrantyInformation":"2 year warranty",
"shippingInformation":"Ships overnight",
"availabilityStatus":"In Stock",
"reviews":[{"rating":4,
"comment":"Great value for money!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Julian Newton",
"reviewerEmail":"julian.newton@x.dummyjson.com"},
{"rating":5,
"comment":"Would buy again!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Madison Collins",
"reviewerEmail":"madison.collins@x.dummyjson.com"},
{"rating":4,
"comment":"Would buy again!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Clara Berry",
"reviewerEmail":"clara.berry@x.dummyjson.com"}],
"returnPolicy":"7 days return policy",
"minimumOrderQuantity":1,
"meta":{"createdAt":"2024-05-23T08:56:21.620Z",
"updatedAt":"2024-05-23T08:56:21.620Z",
"barcode":"7113807059215",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/1.png",
"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/2.png",
"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/3.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Bed/thumbnail.png"},
{"id":12,
"title":"Annibale Colombo Sofa",
"description":"The Annibale Colombo Sofa is a sophisticated and comfortable seating option,featuring exquisite design and premium upholstery for your living room.",
"category":"furniture",
"price":2499.99,
"discountPercentage":18.54,
"rating":3.08,
"stock":16,
"tags":["furniture",
"sofas"],
"brand":"Annibale Colombo",
"sku":"LUU95CQP",
"weight":3,
"dimensions":{"width":20.97,
"height":19.11,
"depth":25.81},
"warrantyInformation":"1 month warranty",
"shippingInformation":"Ships overnight",
"availabilityStatus":"In Stock",
"reviews":[{"rating":5,
"comment":"Very satisfied!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Tyler Davis",
"reviewerEmail":"tyler.davis@x.dummyjson.com"},
{"rating":5,
"comment":"Excellent quality!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Hannah Robinson",
"reviewerEmail":"hannah.robinson@x.dummyjson.com"},
{"rating":3,
"comment":"Waste of money!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Madison Collins",
"reviewerEmail":"madison.collins@x.dummyjson.com"}],
"returnPolicy":"7 days return policy",
"minimumOrderQuantity":1,
"meta":{"createdAt":"2024-05-23T08:56:21.620Z",
"updatedAt":"2024-05-23T08:56:21.620Z",
"barcode":"0426785817074",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/1.png",
"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/2.png",
"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/3.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/furniture/Annibale%20Colombo%20Sofa/thumbnail.png"},
{"id":16,
"title":"Apple",
"description":"Fresh and crisp apples,perfect for snacking or incorporating into various recipes.",
"category":"groceries",
"price":1.99,
"discountPercentage":1.97,
"rating":2.96,
"stock":9,
"tags":["fruits"],
"sku":"QTROUV79",
"weight":8,
"dimensions":{"width":8.29,
"height":5.58,
"depth":12.41},
"warrantyInformation":"2 year warranty",
"shippingInformation":"Ships in 2 weeks",
"availabilityStatus":"In Stock",
"reviews":[{"rating":4,
"comment":"Great product!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Logan Lee",
"reviewerEmail":"logan.lee@x.dummyjson.com"},
{"rating":4,
"comment":"Great product!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Elena Long",
"reviewerEmail":"elena.long@x.dummyjson.com"},
{"rating":1,
"comment":"Not as described!",
"date":"2024-05-23T08:56:21.620Z",
"reviewerName":"Grayson Coleman",
"reviewerEmail":"grayson.coleman@x.dummyjson.com"}],
"returnPolicy":"60 days return policy",
"minimumOrderQuantity":44,
"meta":{"createdAt":"2024-05-23T08:56:21.620Z",
"updatedAt":"2024-05-23T08:56:21.620Z",
"barcode":"2517819903837",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/groceries/Apple/1.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/groceries/Apple/thumbnail.png"},
{"id":101,
"title":"Apple AirPods Max Silver",
"description":"The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio,adaptive EQ,and active noise cancellation. Experience immersive sound in style.",
"category":"mobile-accessories",
"price":549.99,
"discountPercentage":11.7,
"rating":3.11,
"stock":7,
"tags":["electronics",
"over-ear headphones"],
"brand":"Apple",
"sku":"HPK82VDE",
"weight":4,
"dimensions":{"width":7.73,
"height":18.36,
"depth":17.87},
"warrantyInformation":"3 months warranty",
"shippingInformation":"Ships in 1 month",
"availabilityStatus":"In Stock",
"reviews":[{"rating":1,
"comment":"Waste of money!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Harper Kelly",
"reviewerEmail":"harper.kelly@x.dummyjson.com"},
{"rating":3,
"comment":"Not as described!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Abigail Rivera",
"reviewerEmail":"abigail.rivera@x.dummyjson.com"},
{"rating":5,
"comment":"Excellent quality!",
"date":"2024-05-23T08:56:21.624Z",
"reviewerName":"Nora Russell",
"reviewerEmail":"nora.russell@x.dummyjson.com"}],
"returnPolicy":"90 days return policy",
"minimumOrderQuantity":2,
"meta":{"createdAt":"2024-05-23T08:56:21.624Z",
"updatedAt":"2024-05-23T08:56:21.624Z",
"barcode":"9261269777547",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/1.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/thumbnail.png"},
{"id":83,
"title":"Blue & Black Check Shirt",
"description":"The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric,it's suitable for both casual and semi-formal occasions.",
"category":"mens-shirts",
"price":29.99,
"discountPercentage":1.41,
"rating":4.19,
"stock":44,
"tags":["clothing",
"men's shirts"],
"brand":"Fashion Trends",
"sku":"6RJDTVCU",
"weight":6,
"dimensions":{"width":17.25,
"height":27.31,
"depth":20.88},
"warrantyInformation":"No warranty",
"shippingInformation":"Ships in 1 month",
"availabilityStatus":"In Stock",
"reviews":[{"rating":4,
"comment":"Highly recommended!",
"date":"2024-05-23T08:56:21.623Z",
"reviewerName":"Mason Parker",
"reviewerEmail":"mason.parker@x.dummyjson.com"},
{"rating":5,
"comment":"Highly impressed!",
"date":"2024-05-23T08:56:21.623Z",
"reviewerName":"Avery Perez",
"reviewerEmail":"avery.perez@x.dummyjson.com"},
{"rating":5,
"comment":"Fast shipping!",
"date":"2024-05-23T08:56:21.623Z",
"reviewerName":"Nathan Reed",
"reviewerEmail":"nathan.reed@x.dummyjson.com"}],
"returnPolicy":"7 days return policy",
"minimumOrderQuantity":4,
"meta":{"createdAt":"2024-05-23T08:56:21.623Z",
"updatedAt":"2024-05-23T08:56:21.623Z",
"barcode":"8840720880947",
"qrCode":"https://assets.dummyjson.com/public/qr-code.png"},
"images":["https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/1.png",
"https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/2.png",
"https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/3.png",
"https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/4.png"],
"thumbnail":"https://cdn.dummyjson.com/products/images/mens-shirts/Blue%20&%20Black%20Check%20Shirt/thumbnail.png"}],
"total":194,
"skip":0,
"limit":30,
"products": "kannan"
}


# print(value["products"][0]["tags"][0])
print(value["total"])
print(value["products"])